apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-1
 namespace: debian
spec:
  storageClassName: "storageos" # StorageOS storageClass
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi